services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
      - redis
  db:
    image: mongo:latest
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}

  redis:
    image: redis:alpine
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

